name: Auto Dockerize

on:
  push:
    branches: [main]

jobs:
  dockerize:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # optional, for full history

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.DOCKER_IMAGE }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run dockerize and push action
        uses: sitharamsenarath/dockerize-and-push@main
        with:
          image_tag: latest
