name: Auto Dockerize

on:
  push:
    branches: [main]

jobs:
  dockerize:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # optional, for full history
    
      - name: Clone entrypoint script repo
        run: git clone https://github.com/sitharamsenarath/dockerize-and-push.git
    
      - name: Run dockerize and push action
        uses: sitharamsenarath/dockerize-and-push@main
        with:
          image_tag: latest
